apiVersion: v1
kind: Secret
metadata:
  name: sensor-clotho-secret
  namespace: sensor-clotho
  labels:
    app: sensor-clotho
type: Opaque
data:
  BROKER_USER: ${MQTT_BROKER_USER}
  BROKER_PWD: ${MQTT_BROKER_PWD}
---
