apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sensor-clotho-log-data
  namespace: sensor-clotho
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${SENSOR_CLOTHO_STORAGECLASS}
  resources:
    requests:
      storage: 2Gi
---
